matrix:
  include:
    - language: python
      before_script:
        - pip install sphinx
      script:
        - export NUMPYVER:=$(shell python3 -c "import numpy; print(numpy.version.git_revision[:10])")
        - cd docs && GITVER=$(NUMPYVER) make html

    - language: node_js
      script:
        - npm i -g surge
      after_success:
        - bash ./pr_deploy.sh
