matrix:
  include:
    - language: python
      script:
        - pip install sphinx numpy matplotlib IPython
      after_success:
        - bash ./generate_html.sh

    - language: node_js
      script:
        - npm install --save-dev surge
      # after_success:
      #   - bash ./pr_deploy.sh
      deploy:
        provider: surge
        project: ./docs/build/html
        domain: https://pr-${TRAVIS_PULL_REQUEST}-numpy.surge.sh
