matrix:
  include:
    - language: python
      script:
        - pip install sphinx numpy matplotlib IPython
      after_success:
        - bash ./generate_html.sh

    - language: node_js
      script:
        - npm i -g surge
      after_success:
        - bash ./pr_deploy.sh
