project_identifier: poc-translation
api_key: 08bc0e35acaa2b5cc33dae79f91a579f
base_path: .
preserve_hierarchy: true
files:
  - source: /docs/**/*.rst
    translation: /docs/**/%two_letter_code%/%original_file_name%
