project_identifier: poc-translation
api_key: 08bc0e35acaa2b5cc33dae79f91a579f
base_path: .
preserve_hierarchy: true
files:
  - source: /docs/source/about.rst
    translation: /docs/source/%two_letters_code%_%original_file_name%
